import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Montserrat, Space_Grotesk } from "next/font/google";
import { Toaster } from "sonner"; // Correct import

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
className={`${spaceGrotesk.variable} antialiased scroll-smooth bg-white text-gray-900`}
      >
        <Toaster />
        {children}
      </body>
    </html>
  );
}
